In [34]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [35]:
df = pd.read_excel("flight_price.xlsx")
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 1.8 MB

In [37]:
df["Date"] = df["Date_of_Journey"].str.split("/").str[0].astype(int)
df["Month"] = df["Date_of_Journey"].str.split("/").str[1].astype(int)
df["Year"] = df["Date_of_Journey"].str.split("/").str[2].astype(int)

df.drop(columns="Date_of_Journey", inplace=True)

df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [38]:
df["Arrival_Time"] = df["Arrival_Time"].str.split(" ").str[0]

df["Arrival_Hour"] = df["Arrival_Time"].str.split(":").str[0].astype(int)
df["Arrival_Min"] = df["Arrival_Time"].str.split(":").str[1].astype(int)

df.drop(columns="Arrival_Time", inplace=True)

df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [39]:
df["Dep_Hour"] = df["Dep_Time"].str.split(":").str[0].astype(int)
df["Dep_Min"] = df["Dep_Time"].str.split(":").str[1].astype(int)

df.drop(columns="Dep_Time", inplace=True)

df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [40]:
df["Duration_Hour"] = df["Duration"].str.extract(r"(\d+)h").fillna(0).astype(int)
df["Duration_Min"] = df["Duration"].str.extract(r"(\d+)m").fillna(0).astype(int)

df["Total_time_duration"] = df["Duration_Hour"] * 60 + df["Duration_Min"]

df.drop(columns=["Duration","Duration_Hour","Duration_Min"], inplace=True)

df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Total_time_duration
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,13,15,5,50,445
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,12,5,2019,23,30,18,5,325
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,1,3,2019,21,35,16,50,285

In [41]:
df["Total_Stops"] = df["Total_Stops"].fillna(df["Total_Stops"].mode()[0])

In [42]:
df["Total_Stops"].value_counts()

Total_Stops
1 stop      5626
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [43]:
encoder = OrdinalEncoder(
    categories=[["non-stop", "1 stop", "2 stops", "3 stops", "4 stops"]]
)
encoded_array = encoder.fit_transform(df[["Total_Stops"]])

df["Total_Stops"] = encoded_array
df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Total_time_duration
0,IndiGo,Banglore,New Delhi,BLR → DEL,0.0,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2.0,No info,7662,1,5,2019,13,15,5,50,445
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2.0,No info,13882,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1.0,No info,6218,12,5,2019,23,30,18,5,325
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1.0,No info,13302,1,3,2019,21,35,16,50,285

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Airline              10683 non-null  str
 1   Source               10683 non-null  str
 2   Destination          10683 non-null  str
 3   Route                10682 non-null  str
 4   Total_Stops          10683 non-null  float64
 5   Additional_Info      10683 non-null  str
 6   Price                10683 non-null  int64
 7   Date                 10683 non-null  int64
 8   Month                10683 non-null  int64
 9   Year                 10683 non-null  int64
 10  Arrival_Hour         10683 non-null  int64
 11  Arrival_Min          10683 non-null  int64
 12  Dep_Hour             10683 non-null  int64
 13  Dep_Min              10683 non-null  int64
 14  Total_time_duration  10683 non-null  int64
dtypes: float64(1), int64(9), str(5)
memory usage: 1.8 MB

In [45]:
df.drop(columns=["Route"],inplace=True)
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Total_time_duration
0,IndiGo,Banglore,New Delhi,0.0,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,2.0,No info,7662,1,5,2019,13,15,5,50,445
2,Jet Airways,Delhi,Cochin,2.0,No info,13882,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,1.0,No info,6218,12,5,2019,23,30,18,5,325
4,IndiGo,Banglore,New Delhi,1.0,No info,13302,1,3,2019,21,35,16,50,285

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Airline              10683 non-null  str
 1   Source               10683 non-null  str
 2   Destination          10683 non-null  str
 3   Total_Stops          10683 non-null  float64
 4   Additional_Info      10683 non-null  str
 5   Price                10683 non-null  int64
 6   Date                 10683 non-null  int64
 7   Month                10683 non-null  int64
 8   Year                 10683 non-null  int64
 9   Arrival_Hour         10683 non-null  int64
 10  Arrival_Min          10683 non-null  int64
 11  Dep_Hour             10683 non-null  int64
 12  Dep_Min              10683 non-null  int64
 13  Total_time_duration  10683 non-null  int64
dtypes: float64(1), int64(9), str(4)
memory usage: 1.5 MB

In [48]:
encoder = OneHotEncoder(sparse_output=False)
encoded_array = encoder.fit_transform(
    df[
        [
            "Airline",
            "Source",
            "Destination",
            "Additional_Info",
        ]
    ]
)
# print(encoded_array)

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(),
    index=df.index,
)

In [49]:
df = pd.concat(
    [
        df.drop(
            columns=["Airline", "Source", "Destination", "Additional_Info"],
        ),
        encoded_df,
    ],
    axis=1,
)
df.head()

,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Total_time_duration,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,3897,24,3,2019,1,10,22,20,170,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2.0,7662,1,5,2019,13,15,5,50,445,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2.0,13882,9,6,2019,4,25,9,25,1140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,6218,12,5,2019,23,30,18,5,325,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,13302,1,3,2019,21,35,16,50,285,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 43 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Total_Stops                                   10683 non-null  float64
 1   Price                                         10683 non-null  int64
 2   Date                                          10683 non-null  int64
 3   Month                                         10683 non-null  int64
 4   Year                                          10683 non-null  int64
 5   Arrival_Hour                                  10683 non-null  int64
 6   Arrival_Min                                   10683 non-null  int64
 7   Dep_Hour                                      10683 non-null  int64
 8   Dep_Min                                       10683 non-null  int64
 9   Total_time_duration                           10683 non-null  int64
 10  Airline_Air Asia                              10683 non-null  float64
 11  Airline_Air India                             10683 non-null  float64
 12  Airline_GoAir                                 10683 non-null  float64
 13  Airline_IndiGo                                10683 non-null  float64
 14  Airline_Jet Airways                           10683 non-null  float64
 15  Airline_Jet Airways Business                  10683 non-null  float64
 16  Airline_Multiple carriers                     10683 non-null  float64
 17  Airline_Multiple carriers Premium economy     10683 non-null  float64
 18  Airline_SpiceJet                              10683 non-null  float64
 19  Airline_Trujet                                10683 non-null  float64
 20  Airline_Vistara                               10683 non-null  float64
 21  Airline_Vistara Premium economy               10683 non-null  float64
 22  Source_Banglore                               10683 non-null  float64
 23  Source_Chennai                                10683 non-null  float64
 24  Source_Delhi                                  10683 non-null  float64
 25  Source_Kolkata                                10683 non-null  float64
 26  Source_Mumbai                                 10683 non-null  float64
 27  Destination_Banglore                          10683 non-null  float64
 28  Destination_Cochin                            10683 non-null  float64
 29  Destination_Delhi                             10683 non-null  float64
 30  Destination_Hyderabad                         10683 non-null  float64
 31  Destination_Kolkata                           10683 non-null  float64
 32  Destination_New Delhi                         10683 non-null  float64
 33  Additional_Info_1 Long layover                10683 non-null  float64
 34  Additional_Info_1 Short layover               10683 non-null  float64
 35  Additional_Info_2 Long layover                10683 non-null  float64
 36  Additional_Info_Business class                10683 non-null  float64
 37  Additional_Info_Change airports               10683 non-null  float64
 38  Additional_Info_In-flight meal not included   10683 non-null  float64
 39  Additional_Info_No Info                       10683 non-null  float64
 40  Additional_Info_No check-in baggage included  10683 non-null  float64
 41  Additional_Info_No info                       10683 non-null  float64
 42  Additional_Info_Red-eye flight                10683 non-null  float64
dtypes: float64(34), int64(9)
memory usage: 3.5 MB